import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { supabaseServer } from '@/lib/supabaseServer'
import { createCalendarEvent } from '@/lib/googleCalendar'

async function getDoctorRow(email: string) {
  const { data } = await supabaseServer
    .from('users').select('id, role, full_name, email').eq('email', email).single()
  if (!data || data.role !== 'doctor') return null
  return data
}

// GET /api/doctor/appointments
export async function GET() {
  const session = await getServerSession(authOptions)
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const doctor = await getDoctorRow(session.user.email)
  if (!doctor) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const { data, error } = await supabaseServer
    .from('appointments')
    .select('*')
    .eq('doctor_id', doctor.id)
    .order('date', { ascending: true })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  const appointments = (data ?? []).map(a => ({
    id: a.id,
    patientName: a.patient_name,
    patientId: a.patient_id,
    date: a.date,
    time: a.time,
    type: a.type,
    mode: a.mode,
    status: a.status,
    reason: a.reason ?? '',
    initiatedBy: a.initiated_by ?? 'doctor',
    meetLink: a.meet_link ?? null,
    calendarEventId: a.calendar_event_id ?? null,
    calendarEventLink: a.calendar_event_link ?? null,
    avatar: a.patient_name.split(' ')[0],
  }))

  return NextResponse.json({ appointments })
}

// POST /api/doctor/appointments — doctor creates appointment
export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const doctor = await getDoctorRow(session.user.email)
  if (!doctor) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const body = await req.json()
  const { patientName, patientId, date, time, type, mode } = body

  if (!patientName || !date || !time)
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })

  // Try to get patient email for calendar invite
  let patientEmail: string | null = null
  if (patientId) {
    const { data: pu } = await supabaseServer.from('users').select('email').eq('id', patientId).single()
    patientEmail = pu?.email ?? null
  }

  // Create Google Calendar event with Meet link for Online appointments
  let meetLink: string | null = null
  let calendarEventId: string | null = null
  let calendarEventLink: string | null = null

  const accessToken = (session as any).access_token
  if (accessToken) {
    try {
      const attendees = [doctor.email, patientEmail].filter(Boolean) as string[]
      const calResult = await createCalendarEvent(accessToken, {
        summary: `${type ?? 'Consultation'} — ${patientName}`,
        description: `Medical appointment with Dr. ${doctor.full_name ?? 'Doctor'}.\nPatient: ${patientName}\nMode: ${mode ?? 'Offline'}`,
        date,
        time,
        durationMins: 30,
        attendeeEmails: attendees,
      })
      calendarEventId   = calResult.eventId
      calendarEventLink = calResult.eventLink
      // Use the Google Meet link generated by Calendar API for Online appointments
      if (mode === 'Online' && calResult.meetLink) {
        meetLink = calResult.meetLink
      }
    } catch (calErr) {
      console.error('[calendar] Failed to create event:', calErr)
      // Non-fatal — appointment still gets created
    }
  }

  const { data, error } = await supabaseServer
    .from('appointments')
    .insert({
      doctor_id: doctor.id,
      patient_id: patientId ?? null,
      patient_name: patientName,
      date, time, type, mode,
      status: 'Confirmed',
      meet_link: meetLink,
      calendar_event_id: calendarEventId,
      calendar_event_link: calendarEventLink,
      initiated_by: 'doctor',
    })
    .select().single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Notify patient
  if (patientId) {
    const parts: string[] = [
      `Your ${mode} appointment with Dr. ${doctor.full_name ?? 'your doctor'} is confirmed for ${date} at ${time}.`,
    ]
    if (meetLink) parts.push(`Join Google Meet: ${meetLink}`)
    if (calendarEventLink) parts.push(`Calendar event: ${calendarEventLink}`)

    await supabaseServer.from('patient_notifications').insert({
      patient_id: patientId,
      doctor_id: doctor.id,
      title: 'Appointment Confirmed',
      message: parts.join(' '),
      type: 'appointment',
    })
  }

  return NextResponse.json({
    appointment: {
      id: data.id,
      patientName: data.patient_name,
      date: data.date,
      time: data.time,
      type: data.type,
      mode: data.mode,
      status: data.status,
      meetLink: data.meet_link ?? null,
      calendarEventId: data.calendar_event_id ?? null,
      calendarEventLink: data.calendar_event_link ?? null,
      avatar: data.patient_name.split(' ')[0],
    },
  })
}

// PATCH /api/doctor/appointments — confirm / cancel
export async function PATCH(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const doctor = await getDoctorRow(session.user.email)
  if (!doctor) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const { id, status } = await req.json()
  if (!id || !status) return NextResponse.json({ error: 'Missing id or status' }, { status: 400 })

  // Fetch existing appointment
  const { data: existing } = await supabaseServer
    .from('appointments')
    .select('patient_id, patient_name, date, time, mode, meet_link, calendar_event_id, calendar_event_link, type')
    .eq('id', id)
    .single()

  if (!existing) return NextResponse.json({ error: 'Appointment not found' }, { status: 404 })

  let meetLink = existing.meet_link
  let calendarEventId = existing.calendar_event_id
  let calendarEventLink = existing.calendar_event_link

  // On confirmation — create calendar event + Meet link if not already done
  if (status === 'Confirmed' && !calendarEventId) {
    let patientEmail: string | null = null
    if (existing.patient_id) {
      const { data: pu } = await supabaseServer.from('users').select('email').eq('id', existing.patient_id).single()
      patientEmail = pu?.email ?? null
    }

    const accessToken = (session as any).access_token
    if (accessToken) {
      try {
        const attendees = [doctor.email, patientEmail].filter(Boolean) as string[]
        const calResult = await createCalendarEvent(accessToken, {
          summary: `${existing.type ?? 'Consultation'} — ${existing.patient_name}`,
          description: `Medical appointment with Dr. ${doctor.full_name ?? 'Doctor'}.\nPatient: ${existing.patient_name}\nMode: ${existing.mode}`,
          date: existing.date,
          time: existing.time,
          durationMins: 30,
          attendeeEmails: attendees,
        })
        calendarEventId   = calResult.eventId
        calendarEventLink = calResult.eventLink
        if (existing.mode === 'Online' && calResult.meetLink) {
          meetLink = calResult.meetLink
        }
      } catch (calErr) {
        console.error('[calendar] Failed to create event on confirm:', calErr)
      }
    }
  }

  const { error } = await supabaseServer
    .from('appointments')
    .update({
      status,
      meet_link: meetLink,
      calendar_event_id: calendarEventId,
      calendar_event_link: calendarEventLink,
    })
    .eq('id', id)
    .eq('doctor_id', doctor.id)

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Notify patient
  if (existing.patient_id) {
    const parts: string[] = [
      `Your appointment on ${existing.date} at ${existing.time} has been ${status.toLowerCase()}.`,
    ]
    if (status === 'Confirmed') {
      if (meetLink) parts.push(`Join Google Meet: ${meetLink}`)
      if (calendarEventLink) parts.push(`Calendar invite sent — check your email.`)
    }

    await supabaseServer.from('patient_notifications').insert({
      patient_id: existing.patient_id,
      doctor_id: doctor.id,
      title: `Appointment ${status}`,
      message: parts.join(' '),
      type: 'appointment',
    })
  }

  return NextResponse.json({ success: true, meetLink, calendarEventLink })
}
