// Auto-generated by `npx boneyard-js build`
// Run that command after your dev server is up to populate this file with real bone data.
// Until then, skeletons will fall back to the `fallback` prop or render nothing.

// Example of what gets generated:
// import { registerBones } from 'boneyard-js'
// import dashboardOverview from './dashboard-overview.bones.json'
// registerBones('dashboard-overview', dashboardOverview)
