/**
 * Symptom list for the Apex Disease Prediction Network (Human-Health_model)
 * Maps display names → API keys (snake_case / comma-separated format)
 * The API accepts any subset; unrecognised keys are silently ignored.
 */

export interface Symptom {
  display: string; // Human-readable label shown in the UI
  key: string;     // Exact key sent to POST /predict
}

// Converts a display name to the snake_case key the model expects
export function toApiKey(display: string): string {
  return display
    .toLowerCase()
    .replace(/\s*\(([^)]+)\)/g, '_($1)') // keep parenthetical content
    .replace(/[,]/g, ',')                 // keep commas as-is (model uses them)
    .replace(/ /g, '_');
}

// Full symptom list derived from lib/symptoms.json display names
const RAW_SYMPTOMS: string[] = [
  "Itching", "Skin Rash", "Nodal Skin Eruptions", "Continuous Sneezing", "Shivering",
  "Chills", "Joint Pain", "Stomach Pain", "Acidity", "Ulcers On Tongue",
  "Muscle Wasting", "Vomiting", "Burning Micturition", "Spotting Urination", "Fatigue",
  "Weight Gain", "Anxiety", "Cold Hands And Feets", "Mood Swings", "Weight Loss",
  "Restlessness", "Lethargy", "Patches In Throat", "Irregular Sugar Level", "Cough",
  "High Fever", "Sunken Eyes", "Breathlessness", "Sweating", "Dehydration",
  "Indigestion", "Headache", "Yellowish Skin", "Dark Urine", "Nausea",
  "Loss Of Appetite", "Pain Behind The Eyes", "Back Pain", "Constipation", "Abdominal Pain",
  "Diarrhoea", "Mild Fever", "Yellow Urine", "Yellowing Of Eyes", "Acute Liver Failure",
  "Fluid Overload", "Swelling Of Stomach", "Swelled Lymph Nodes", "Malaise",
  "Blurred And Distorted Vision", "Phlegm", "Throat Irritation", "Redness Of Eyes",
  "Sinus Pressure", "Runny Nose", "Congestion", "Chest Pain", "Weakness In Limbs",
  "Fast Heart Rate", "Pain During Bowel Movements", "Pain In Anal Region", "Bloody Stool",
  "Irritation In Anus", "Neck Pain", "Dizziness", "Cramps", "Bruising", "Obesity",
  "Swollen Legs", "Swollen Blood Vessels", "Puffy Face And Eyes", "Enlarged Thyroid",
  "Brittle Nails", "Swollen Extremeties", "Excessive Hunger", "Extra Marital Contacts",
  "Drying And Tingling Lips", "Slurred Speech", "Knee Pain", "Hip Joint Pain",
  "Muscle Weakness", "Stiff Neck", "Swelling Joints", "Movement Stiffness",
  "Spinning Movements", "Loss Of Balance", "Unsteadiness", "Weakness Of One Body Side",
  "Loss Of Smell", "Bladder Discomfort", "Foul Smell Of Urine", "Continuous Feel Of Urine",
  "Passage Of Gases", "Internal Itching", "Toxic Look (Typhos)", "Depression",
  "Irritability", "Muscle Pain", "Altered Sensorium", "Red Spots Over Body", "Belly Pain",
  "Abnormal Menstruation", "Dischromic Patches", "Watering From Eyes", "Increased Appetite",
  "Polyuria", "Family History", "Mucoid Sputum", "Rusty Sputum", "Lack Of Concentration",
  "Visual Disturbances", "Receiving Blood Transfusion", "Receiving Unsterile Injections",
  "Coma", "Stomach Bleeding", "Distention Of Abdomen", "History Of Alcohol Consumption",
  "Blood In Sputum", "Prominent Veins On Calf", "Palpitations", "Painful Walking",
  "Pus Filled Pimples", "Blackheads", "Scurring", "Skin Peeling", "Silver Like Dusting",
  "Small Dents In Nails", "Inflammatory Nails", "Blister", "Red Sore Around Nose",
  "Yellow Crust Ooze",
  // Extended symptom set from the new model dataset
  "Abdominal Pain Or Cramps", "Achy Muscles And Bones", "Bad Taste In The Mouth",
  "Blisters", "Bloody Stools", "Blurred Vision (Intermittent)", "Body Aches",
  "Burning Sensation In The Eyes", "Clustered Sores", "Cotton-Like Sensation In The Mouth",
  "Diarrhea", "Difficulty Sleeping", "Difficulty Swallowing", "Discolored Marks",
  "Discolored Sores", "Dry Or Watery Eyes (Epiphora)", "Exhaustion", "Fever",
  "Feverish", "General Discomfort", "Generally Feeling Unwell (Malaise)", "Hacking Cough",
  "Headache And Body Aches", "Infection From Scratched Skin", "Itchiness",
  "Itchy Or Irritated Eyes", "Light Sensitivity (Photophobia)", "Loss Of Taste",
  "Low-Grade Fever", "Low Fever", "Mild Eye Pain Or Discomfort", "Mild Fatigue",
  "Mild Hacking Cough", "Mouth Sores", "Muscle Aches", "Myalgias", "Nasal Discharge",
  "Nausea Or Vomiting", "Pain", "Pain While Chewing Or Swallowing", "Pale Skin Around Lips",
  "Pink Eye", "Rash", "Rash On Face", "Rash On Hands And Feet", "Rashes",
  "Red And Swollen Tonsils", "Red And Watery Eyes", "Red Eyes", "Red Lines In Body Folds",
  "Red Rash On The Body", "Red Spots", "Redness", "Redness In The White Of The Eye",
  "Running Nose", "Runny Or Stuffy Nose", "Sensation Of A Foreign Object In The Eye",
  "Severe Coughing Fits", "Slight Bleeding If Spots Are Scraped",
  "Small White Spots Inside The Cheeks", "Sneezing", "Sore And Red Throat With Patches",
  "Sore Muscles", "Sore Throat", "Soreness Or Burning In The Mouth", "Sores From Scratching",
  "Sores In Mouth", "Sores On The Scalp", "Stomach Cramps", "Strawberry Tongue",
  "Swelling", "Swollen Eyelids (Blepharitis)", "Swollen Glands", "Swollen Joints",
  "Swollen Lymph Nodes", "Testicle Pain And Tenderness", "Tickling Feeling",
  "Tickling Sensation In Hair", "Tiredness", "Trouble Chewing", "Trouble Sleeping",
  "Visible Lice On The Scalp", "Vomiting After Coughing", "Watering Eyes",
  "White Patches On Tonsils", "Whooping Cough", "Yellow Crust",
  "Anxiety And Nervousness", "Shortness Of Breath", "Depressive Or Psychotic Symptoms",
  "Sharp Chest Pain", "Insomnia", "Abnormal Involuntary Movements", "Chest Tightness",
  "Irregular Heartbeat", "Breathing Fast", "Hoarse Voice", "Difficulty Speaking",
  "Nasal Congestion", "Throat Swelling", "Diminished Hearing", "Lump In Throat",
  "Throat Feels Tight", "Difficulty In Swallowing", "Skin Swelling", "Retention Of Urine",
  "Groin Mass", "Leg Pain", "Hip Pain", "Suprapubic Pain", "Blood In Stool",
  "Lack Of Growth", "Emotional Symptoms", "Elbow Weakness", "Back Weakness",
  "Pus In Sputum", "Swelling Of Scrotum", "Pain In Testicles", "Flatulence",
  "Pus Draining From Ear", "Jaundice", "Mass In Scrotum", "White Discharge From Eye",
  "Irritable Infant", "Abusing Alcohol", "Fainting", "Hostile Behavior", "Drug Abuse",
  "Sharp Abdominal Pain", "Feeling Ill", "Vaginal Itching", "Vaginal Dryness",
  "Painful Urination", "Involuntary Urination", "Pain During Intercourse",
  "Frequent Urination", "Lower Abdominal Pain", "Vaginal Discharge", "Blood In Urine",
  "Hot Flashes", "Intermenstrual Bleeding", "Hand Or Finger Pain", "Wrist Pain",
  "Hand Or Finger Swelling", "Arm Pain", "Wrist Swelling", "Arm Stiffness Or Tightness",
  "Arm Swelling", "Hand Or Finger Stiffness Or Tightness", "Wrist Stiffness Or Tightness",
  "Lip Swelling", "Toothache", "Abnormal Appearing Skin", "Skin Lesion",
  "Acne Or Pimples", "Dry Lips", "Facial Pain", "Mouth Ulcer", "Skin Growth",
  "Eye Deviation", "Diminished Vision", "Double Vision", "Cross-Eyed",
  "Pain In Eye", "Eye Moves Abnormally", "Abnormal Movement Of Eyelid",
  "Foreign Body Sensation In Eye", "Irregular Appearing Scalp", "Low Back Pain",
  "Pain Of The Anus", "Pain During Pregnancy", "Pelvic Pain", "Impotence",
  "Infant Spitting Up", "Vomiting Blood", "Regurgitation", "Burning Abdominal Pain",
  "Wheezing", "Peripheral Edema", "Neck Mass", "Ear Pain", "Jaw Swelling",
  "Mouth Dryness", "Neck Swelling", "Foot Or Toe Pain", "Bowlegged Or Knock-Kneed",
  "Ankle Pain", "Bones Are Painful", "Knee Weakness", "Elbow Pain", "Knee Swelling",
  "Skin Moles", "Knee Lump Or Mass", "Problems With Movement",
  "Knee Stiffness Or Tightness", "Leg Swelling", "Foot Or Toe Swelling", "Heartburn",
  "Smoking Problems", "Infant Feeding Problem", "Recent Weight Loss",
  "Problems With Shape Or Size Of Breast", "Underweight", "Difficulty Eating",
  "Scanty Menstrual Flow", "Vaginal Pain", "Vaginal Redness", "Vulvar Irritation",
  "Weakness", "Decreased Heart Rate", "Increased Heart Rate",
  "Bleeding Or Discharge From Nipple", "Ringing In Ear", "Plugged Feeling In Ear",
  "Itchy Ear(S)", "Frontal Headache", "Fluid In Ear", "Neck Stiffness Or Tightness",
  "Spots Or Clouds In Vision", "Eye Redness", "Lacrimation", "Itchiness Of Eye",
  "Blindness", "Eye Burns Or Stings", "Itchy Eyelid", "Feeling Cold",
  "Decreased Appetite", "Excessive Appetite", "Excessive Anger", "Loss Of Sensation",
  "Focal Weakness", "Slurring Words", "Disturbance Of Memory", "Paresthesia",
  "Side Pain", "Shoulder Pain", "Shoulder Stiffness Or Tightness", "Shoulder Weakness",
  "Arm Cramps Or Spasms", "Shoulder Swelling", "Tongue Lesions", "Leg Cramps Or Spasms",
  "Abnormal Appearing Tongue", "Ache All Over", "Lower Body Pain",
  "Problems During Pregnancy", "Spotting Or Bleeding During Pregnancy",
  "Cramps And Spasms", "Upper Abdominal Pain", "Stomach Bloating",
  "Changes In Stool Appearance", "Unusual Color Or Odor To Urine", "Kidney Mass",
  "Swollen Abdomen", "Leg Stiffness Or Tightness", "Difficulty Breathing", "Rib Pain",
  "Muscle Stiffness Or Tightness", "Pallor", "Hand Or Finger Lump Or Mass", "Groin Pain",
  "Abdominal Distention", "Melena", "Flushing", "Coughing Up Sputum", "Seizures",
  "Delusions Or Hallucinations", "Shoulder Cramps Or Spasms",
  "Joint Stiffness Or Tightness", "Pain Or Soreness Of Breast",
  "Excessive Urination At Night", "Bleeding From Eye", "Rectal Bleeding",
  "Temper Problems", "Coryza", "Wrist Weakness", "Eye Strain", "Hemoptysis",
  "Lymphedema", "Skin On Leg Or Foot Looks Infected", "Allergic Reaction",
  "Congestion In Chest", "Muscle Swelling", "Pus In Urine",
  "Abnormal Size Or Shape Of Ear", "Low Back Weakness", "Sleepiness", "Apnea",
  "Abnormal Breathing Sounds", "Excessive Growth", "Elbow Cramps Or Spasms",
  "Feeling Hot And Cold", "Blood Clots During Menstrual Periods",
  "Absence Of Menstruation", "Pulling At Ears", "Gum Pain", "Redness In Ear",
  "Fluid Retention", "Flu-Like Syndrome", "Sinus Congestion", "Painful Sinuses",
  "Fears And Phobias", "Recent Pregnancy", "Uterine Contractions", "Burning Chest Pain",
  "Back Cramps Or Spasms", "Stiffness All Over", "Low Back Cramps Or Spasms",
  "Back Mass Or Lump", "Nosebleed", "Long Menstrual Periods", "Heavy Menstrual Flow",
  "Unpredictable Menstruation", "Painful Menstruation", "Infertility",
  "Frequent Menstruation", "Mass On Eyelid", "Swollen Eye", "Eyelid Swelling",
  "Eyelid Lesion Or Rash", "Unwanted Hair", "Irregular Appearing Nails",
  "Itching Of Skin", "Hurts To Breath", "Nailbiting",
  "Skin On Arm Or Hand Looks Infected", "Skin Irritation", "Itchy Scalp",
  "Hip Swelling", "Incontinence Of Stool", "Foot Or Toe Cramps Or Spasms", "Warts",
  "Bumps On Penis", "Too Little Hair", "Foot Or Toe Lump Or Mass",
  "Mass Or Swelling Around The Anus", "Low Back Swelling", "Ankle Swelling",
  "Hip Lump Or Mass", "Drainage In Throat", "Dry Or Flaky Scalp",
  "Premenstrual Tension Or Irritability", "Feeling Hot", "Feet Turned In",
  "Foot Or Toe Stiffness Or Tightness", "Pelvic Pressure", "Elbow Swelling",
  "Elbow Stiffness Or Tightness", "Early Or Late Onset Of Menopause", "Mass On Ear",
  "Bleeding From Ear", "Hand Or Finger Weakness", "Low Self-Esteem",
  "Itching Of The Anus", "Swollen Or Red Tonsils", "Irregular Belly Button",
  "Swollen Tongue", "Lip Sore", "Vulvar Sore", "Hip Stiffness Or Tightness",
  "Mouth Pain", "Arm Weakness", "Leg Lump Or Mass", "Disturbance Of Smell Or Taste",
  "Discharge In Stools", "Penis Pain", "Loss Of Sex Drive", "Obsessions And Compulsions",
  "Antisocial Behavior", "Neck Cramps Or Spasms", "Pupils Unequal", "Poor Circulation",
  "Thirst", "Sleepwalking", "Skin Oiliness", "Bladder Mass", "Knee Cramps Or Spasms",
  "Premature Ejaculation", "Leg Weakness", "Posture Problems", "Bleeding In Mouth",
  "Tongue Bleeding", "Change In Skin Mole Size Or Color", "Penis Redness",
  "Penile Discharge", "Shoulder Lump Or Mass", "Cloudy Eye", "Hysterical Behavior",
  "Arm Lump Or Mass", "Nightmares", "Bleeding Gums", "Pain In Gums", "Bedwetting",
  "Diaper Rash", "Lump Or Mass Of Breast", "Vaginal Bleeding After Menopause",
  "Infrequent Menstruation", "Mass On Vulva", "Jaw Pain", "Itching Of Scrotum",
  "Postpartum Problems Of The Breast", "Eyelid Retracted", "Hesitancy",
  "Elbow Lump Or Mass", "Throat Redness", "Joint Swelling", "Tongue Pain",
  "Redness In Or Around Nose", "Wrinkles On Skin", "Foot Or Toe Weakness",
  "Hand Or Finger Cramps Or Spasms", "Back Stiffness Or Tightness",
  "Wrist Lump Or Mass", "Skin Pain", "Low Back Stiffness Or Tightness",
  "Low Urine Output", "Skin On Head Or Neck Looks Infected", "Stuttering Or Stammering",
  "Problems With Orgasm", "Nose Deformity", "Lump Over Jaw", "Sore In Nose",
  "Hip Weakness", "Back Swelling", "Ankle Stiffness Or Tightness", "Ankle Weakness",
  "Neck Weakness",
];

export const SYMPTOMS: Symptom[] = RAW_SYMPTOMS.map((display) => ({
  display,
  key: toApiKey(display),
}));

// Build a lookup map for fast access
export const SYMPTOM_MAP = new Map<string, string>(
  SYMPTOMS.map(({ display, key }) => [display, key])
);
